<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>01_System_Test_Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>4ddcd14e-17fd-4c2f-89bc-53d98cac5203</testSuiteGuid>
   <testCaseLink>
      <guid>0185279f-2f68-4fb6-bfe3-1b15a0d6be19</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02_System_Tests/Instance_Retrieval/instance_retrieval_on_demand</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4641effc-bba9-4b61-9b83-9e8fabdf6497</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/users</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>4641effc-bba9-4b61-9b83-9e8fabdf6497</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>logged_in_user</value>
         <variableId>4d487ba2-8e09-43bf-a901-0d5e8d0d863d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>66b85cf4-d809-4ea5-9177-4b7ab3cbc9e9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02_System_Tests/Instance_Creation/instance_creation_with_hello_world_message</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>abfee6a4-e3fe-411b-9e5d-46549a275014</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>600fd8e6-e697-4785-888a-9ace74a6ead3</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
