<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>03_Browser_Test_suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>71e45036-3109-4038-9704-17fd4a9c78b7</testSuiteGuid>
   <testCaseLink>
      <guid>d1272763-1f49-4d00-844c-ef327f83c9c3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02_System_Tests/Instance_Creation/instance_creation_with_hello_world_message</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>abfee6a4-e3fe-411b-9e5d-46549a275014</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>600fd8e6-e697-4785-888a-9ace74a6ead3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>08042083-fe74-4e10-b3ba-88e0fd6aec96</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f8511844-4ecd-4805-90a5-fe90de8c2f3b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02_System_Tests/Instance_Retrieval/instance_retrieval_on_demand</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d487ba2-8e09-43bf-a901-0d5e8d0d863d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5adb212-7451-40b6-ab3a-a3c5cb90ad0c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
