<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>created_instance_id</name>
   <tag></tag>
   <elementGuidId>57c943d9-ef56-48ae-b3c3-33ee7913e3c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Congrats! Your EC2 instance created.'])[1]/following::b[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>a9a028a1-1772-43d2-9d3c-cb460daad886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Instance id: ec2.Instance(id='i-009e6026a2d236886')</value>
      <webElementGuid>b37f8cb9-e1ae-4a7d-9ee4-f98a21f73b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/b[1]</value>
      <webElementGuid>b8d77e0f-9ae4-4e87-89f5-d7fe05633888</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Congrats! Your EC2 instance created.'])[1]/following::b[1]</value>
      <webElementGuid>09e794eb-7965-4736-b326-af8882564ba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::b[1]</value>
      <webElementGuid>84204e3b-39a4-4d13-a078-9e046648981c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::b[1]</value>
      <webElementGuid>e31373fd-abae-4670-ad0e-3ae464546684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b</value>
      <webElementGuid>3f2644d9-60e8-4a75-8e59-e84910bbd344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = concat(&quot;Instance id: ec2.Instance(id=&quot; , &quot;'&quot; , &quot;i-009e6026a2d236886&quot; , &quot;'&quot; , &quot;)&quot;) or . = concat(&quot;Instance id: ec2.Instance(id=&quot; , &quot;'&quot; , &quot;i-009e6026a2d236886&quot; , &quot;'&quot; , &quot;)&quot;))]</value>
      <webElementGuid>b61f40b7-fee2-41bf-acd7-20bfa9d0a341</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
