<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>instances_on_show_page</name>
   <tag></tag>
   <elementGuidId>5f91a3e3-342a-43eb-868c-5153a73379d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('(', &quot;'&quot;, 'i-0f76276b845b06574', &quot;'&quot;, ', ', &quot;'&quot;, 'terminated', &quot;'&quot;, ', ', &quot;'&quot;, '', &quot;'&quot;, ')')])[1]/following::li[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(contains(text(), concat(&quot;(&quot; , &quot;'&quot; , &quot;i-0da6f9f607587c1da&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;running&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;ec2-3-86-229-246.compute-1.amazonaws.com&quot; , &quot;'&quot; , &quot;)&quot;)) or contains(., concat(&quot;(&quot; , &quot;'&quot; , &quot;i-0da6f9f607587c1da&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;running&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;ec2-3-86-229-246.compute-1.amazonaws.com&quot; , &quot;'&quot; , &quot;)&quot;)))]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>3c6b1284-b3c5-42c2-bbd6-33ff3b6ad848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${created_instance}</value>
      <webElementGuid>5b9ef0f7-17b5-4293-bfa9-32c70a7ca19e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/ul[1]/li[4]</value>
      <webElementGuid>3651aa22-5b1e-4126-af07-831a6ebff631</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('(', &quot;'&quot;, 'i-0f76276b845b06574', &quot;'&quot;, ', ', &quot;'&quot;, 'terminated', &quot;'&quot;, ', ', &quot;'&quot;, '', &quot;'&quot;, ')')])[1]/following::li[1]</value>
      <webElementGuid>f5300110-204f-45dd-b4c0-7942ddb2e4d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('(', &quot;'&quot;, 'i-0c27be63318bf572b', &quot;'&quot;, ', ', &quot;'&quot;, 'terminated', &quot;'&quot;, ', ', &quot;'&quot;, '', &quot;'&quot;, ')')])[1]/following::li[2]</value>
      <webElementGuid>5e0b6ffd-69ab-4c0f-a788-ac6100643e54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::li[1]</value>
      <webElementGuid>645c1579-eba9-475e-9e99-3ca4d23f5e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::li[1]</value>
      <webElementGuid>b44b609b-1bcd-43df-931e-4b9e99a0805a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]</value>
      <webElementGuid>fcd69b8f-8056-4fe3-93ee-b0cfad9c1fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = concat(&quot;(&quot; , &quot;'&quot; , &quot;i-0da6f9f607587c1da&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;running&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;ec2-3-86-229-246.compute-1.amazonaws.com&quot; , &quot;'&quot; , &quot;)&quot;) or . = concat(&quot;(&quot; , &quot;'&quot; , &quot;i-0da6f9f607587c1da&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;running&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;ec2-3-86-229-246.compute-1.amazonaws.com&quot; , &quot;'&quot; , &quot;)&quot;))]</value>
      <webElementGuid>e1b0a1fa-8d5e-48b6-984d-64147df3e687</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
