<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>show_instances_button</name>
   <tag></tag>
   <elementGuidId>e50f6acd-dd18-47c3-8758-8a9b9e7d2e51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Show instances']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f776b366-5ef0-4a37-b7c1-29426fb809dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>file_submit</value>
      <webElementGuid>c66ac17d-d48e-4b24-bcad-fd771b26bc25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>ee5ebf78-bc7d-4846-830c-f6d1238e513d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Show instances</value>
      <webElementGuid>68751913-6a0b-4264-a5fe-497f7d572a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/form[@class=&quot;grid&quot;]/center[1]/input[@class=&quot;file_submit&quot;]</value>
      <webElementGuid>a7cbb08a-5c36-4667-a484-3593aeb762af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Show instances']</value>
      <webElementGuid>9c37e9a1-0699-4bd9-bd7f-a6d58e80c4f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[2]/center/input</value>
      <webElementGuid>e263384d-ec0b-4a01-b47d-d4debd6a0999</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'Submit']</value>
      <webElementGuid>bc2d7868-26bb-4c44-ac42-f26bbab6ebc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
