<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>show_instances_status_page</name>
   <tag></tag>
   <elementGuidId>7fe5b14e-58c6-4637-8f85-e76f31a8887b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Show instances']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.file_submit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a1ecf3c-82f6-4c99-b0b5-24446564478c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>file_submit</value>
      <webElementGuid>11838961-beec-4dc4-9ab8-589d35b3b38b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>a4be320c-adb6-43ba-b186-bd0958d99be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Show instances</value>
      <webElementGuid>e2b6d70e-c033-48f7-8d53-a1cf5d0ce371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/form[@class=&quot;grid&quot;]/center[1]/input[@class=&quot;file_submit&quot;]</value>
      <webElementGuid>2875f3c3-2a91-4589-90d1-c69bfe1c963e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Show instances']</value>
      <webElementGuid>4db97fd4-87a8-4db9-ac92-791b6cfc6a47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>016438cc-29bb-4000-af06-119f310f8902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'Submit']</value>
      <webElementGuid>a3d93dd4-5b74-487f-8198-436ed60f68d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
